GET http://localhost:3001/products

###
PUT http://localhost:3001/products
content-type: application/json

{
  "name": "Aaaargh Says the Man by Jean Paul Sartre",
  "desc": "Aaaargh indeed"
}
###
PUT http://localhost:3001/products
content-type: application/json

{
  "product_id": "a34fb182-159f-45b7-9a18-ccc0be8f35f6",
  "desc": "10 out of 10, would art again"
}
